version: "3"
services:

chromedriver:
    image: selenium/standalone-chrome
    ports: 
      - "4444:4444"

steam_parser:
    build: .
    volumes:
      - ./script/:/script
    links:
      - chromedriver
